config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  resources :products do
    collection do
      get "uncategorized", to: "products#uncategorized"
    end
    resource :buy_now, only: %i[ show create ], controller: :buy_now do # controller adicionado para que não fique automaticamente no plural
      get "success", on: :collection
    end
  end

  resources :carts, only: %i[ show create destroy ] do
    get "checkout", on: :member, to: "carts#checkout" # member to add the specific id to the url (carts/:id/checkout)
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end

  resource :admin, only: [ :show ], controller: :admin

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "products#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  before_create :set_secret_id

  enum :status, [ "pending", "complete" ]

  private

  def set_secret_id
    self.secret_id = SecureRandom.uuid + DateTime.now.to_i.to_s # enhance security by adding timestamp
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_product, only: %i[ create destroy ]

  def create
    @current_cart.cart_items.create(product_id: @product.id)
  end

  def show
  end

  def checkout
  end

  def destroy
    @cart_item = @current_cart.cart_items.find_by_product_id(@product.id)
    @cart_item.destroy
    redirect_to cart_path(@current_cart)
  end

  def stripe_session
    session = Stripe::Checkout::Session.create({
      ui_mode: "embedded",
      line_items: [ {
          # Provide the exact Price ID (e.g. pr_1234) of the product you want to sell
          price_data: {
            currency: "usd",
            unit_amount: (@current_cart.products.sum(&:price) * 100).to_i,
            product_data: {
              name: @current_cart.products.map(&:name).join("; ")
            }
          },
          quantity: 1
        } ],
        shipping_address_collection: {
          allowed_countries: STRIPE_SUPPORTED_COUNTRIES
        },
        mode: "payment",
        return_url: success_cart_url(@current_cart.secret_id)
    })

    render json: { clientSecret: session.client_secret }
  end

  def success
    if @current_cart.cart_items.any?
      session[:current_cart_id] = nil
    end
    @purchased_cart = Cart.find_by_secret_id(params[:id])
    redirect_to root_path if !@purchased_cart
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end
end

app/views/carts/checkout.html.erb
<div class="w-full grid md:grid-cols-2">
  <div class="w-full flex flex-col items-center md:pt-8">
    <h1 class="text-5xl font-semibold font-serif text-indigo-900 text-center">Your Cart</h1>
    <br>
    <p>You have <%= @current_cart.cart_items.count %> product(s) in your cart.</p>
    <br>
    <div class="mx-auto flex flex-col gap-2 items-center">
      <% @current_cart.products.each do |product| %>
        <div class="flex gap-2 font-semibold justify-between bg-gray-400/75 p-2 rounded-lg">
          <p class="text-lg text-indigo-100"> <%= product.name %></p>
          <p class="text-lg text-green-700"> <%= number_to_currency product.price %></p>
        </div>
      <% end %>
    </div>
  </div>

  <div data-controller="stripe-checkout" data-stripe-checkout-url-value="<%= stripe_session_cart_path(@current_cart.secret_id) %>">
  </div>
</div>

app/views/carts/create.turbo_stream.erb
<%# updates add to cart button and cart count %>

<%= turbo_stream.update("add-to-cart", partial: "products/add_to_cart", locals: {product: @product}) %>
<%= turbo_stream.update("cart", partial: "layouts/cart", locals: { cart: @current_cart })%>

app/views/carts/show.html.erb
<div class="w-full flex flex-col items-center">
  <div class="flex justify-between w-full items-center">
    <div class="flex flex-col gap-4">
      <h1 class="text-5xl font-semibold font-serif text-indigo-900">Your cart</h1>
      <% if @current_cart.cart_items.any? %>
        <p class="text-lg">You have <%= @current_cart.cart_items.count %> item(s) in your cart.</p>
      <% else %>
        <p class="text-lg">Your cart is empty.</p>
      <% end %>
    </div>

    <%= link_to "Checkout Now", checkout_cart_path(@current_cart.secret_id), class:"rounded-lg font-semibold p-4 text-center text-xl bg-yellow-400 hover:bg-yellow-500" %>
  </div>
  <br>
  
  <div id="products" class="min-w-full grid md:grid-cols-4 gap-8 mb-8">
    <% @current_cart.products.each do |product| %>
      <div>
        <%= render "products/product", product: product%>
        <br>
        <%= link_to "Remove from Cart", cart_path(@current_cart.secret_id, product_id: product.id), class: "p-2 rounded-lg bg-red-600 text-red-200 font-semibold hover:bg-red-800", 
              data:{ turbo_method: "delete" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/carts/success.html.erb
<div class="w-full flex flex-col items-center md:pt-8">
  <div class="w-full mb-8 flex flex-col items-center">
    <h2 class="text-4xl font-semibold text-indigo-100 mb-4">Thank you for purchasing!</h2>
    <p class="text-2xl font-semibold text-indigo-50 mb-4">Your products will be shipped soon.</p>
    <div class="relative w-48 h-48 mx-auto" style="background-image: url('<%= asset_path('delivery.gif') %>'); background-size: contain; background-repeat: no-repeat; background-position: center;">
    </div>
  </div>
  <div class="mx-auto flex flex-col gap-2 items-center">
    <% @purchased_cart.products.each do |product| %>
      <div class="flex gap-2 font-semibold justify-between bg-gray-400/75 p-2 rounded-lg">
        <p class="text-lg text-indigo-100"> <%= product.name %></p>
        <p class="text-lg text-green-700"> <%= number_to_currency product.price %></p>
      </div>
    <% end %>
  </div>
</div>