config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  resources :products do
    collection do
      get "uncategorized", to: "products#uncategorized"
    end
    resource :buy_now, only: %i[ show create ], controller: :buy_now do # controller adicionado para que não fique automaticamente no plural
      get "success", on: :collection
    end
  end

  resources :carts, only: %i[ show create destroy ] do
    get "checkout", on: :member, to: "carts#checkout" # member to add the specific id to the url (carts/:id/checkout)
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end

  resource :admin, only: [ :show ], controller: :admin

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "products#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_rich_text :description
  has_one_attached :image
  has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin_privileges, except: %i[ index show ]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :description, :image ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category do %> 
  <div id="<%= dom_id category %>" class="relative flex flex-col items-center">
    <% if category.image.attached? %>
      <%= image_tag category.image, class: "w-30 h-30 object-cover rounded-lg hover:brightness-60 bg-white transition-all duration-250" %>
    <% else %>
      <%= image_tag "placeholder.jpg", class: "w-50 h-70 object-cover rounded-lg", alt: "No Image" %> 
      <p class="text-sm text-gray-500 mt-2">Imagem não disponível</p> 
    <% end %>
    <p class="text-lg text-blue-900 font-bold mt-2"><%= category.name %></p>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul class="list-disc ml-6">
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full bg-gray-200", {"border-gray-400 focus:outline-blue-600": category.errors[:name].none?, "border-red-400 focus:outline-red-600": category.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_textarea :description, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full bg-gray-200", {"border-gray-400 focus:outline-blue-600": category.errors[:description].none?, "border-red-400 focus:outline-red-600": category.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full bg-gray-200", {"border-gray-400 focus:outline-blue-600": category.errors[:image].none?, "border-red-400 focus:outline-red-600": category.errors[:image].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="custom-heading">Categories</h1>

  <div id="categories" class="min-w-full grid md:grid-cols-4 gap-8">
    <% if @categories.any? %>
      <% @categories.each do |category| %>
        <%= render category %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No categories found.</p>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<div class="mx-auto md:w-2/3 w-full mb-8">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full mb-8 text-center">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice">
      <%= notice %>
    </p>
  <% end %>

  <div class="relative flex flex-col items-center">
    <h1 class="custom-heading mb-10"><%= @category.name %></h1>
    <% if @category.image.attached? %>
      <%= image_tag(@category.image, class: "h-50 w-50 object-cover rounded-lg mb-2") %>
    <% end %>
  </div>

  <div class="text-xl font-bold">
    <% if @category.description? %>
      <%= @category.description %>
    <% else %> 
      <p class="text-gray-500">No description available</p>
    <% end %>
  </div>

  <div id="products" class="min-w-full grid md:grid-cols-4 gap-8">
    <% if @category.products.any? %>
      <% @category.products.each do |product| %>
        <%= render "products/product", product: product %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No products found.</p>
    <% end %>
  </div>
  
  <% if current_admin %>
    <div class="flex justify-center flex-wrap items-center gap-4 mt-10">
      <%= link_to "Edit this category", edit_category_path(@category), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-400 font-medium" %>
      <%= link_to "Back to categories", categories_path, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-400 font-medium" %>
      <%= button_to "Destroy this category", @category, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-700 font-medium" %>
    </div>
  <% end %>
</div>