config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  resources :products do
    collection do
      get "uncategorized", to: "products#uncategorized"
    end
    resource :buy_now, only: %i[ show create ], controller: :buy_now do # controller adicionado para que não fique automaticamente no plural
      get "success", on: :collection
    end
  end

  resources :carts, only: %i[ show create destroy ] do
    get "checkout", on: :member, to: "carts#checkout" # member to add the specific id to the url (carts/:id/checkout)
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end

  resource :admin, only: [ :show ], controller: :admin

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_rich_text :description
  has_many_attached :images
  belongs_to :category, optional: true
  has_many :cart_items, dependent: :destroy
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin_privileges, except: %i[ index show uncategorized ]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    new_product_params = product_params.to_unsafe_h
    new_product_params.delete("images") if new_product_params["images"].all?(&:blank?)

    respond_to do |format|
      if @product.update(new_product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def uncategorized
    @products = Product.where(category_id: nil)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.require(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart.html.erb
<div id="add-to-cart" class="w-full flex">
  <% if @current_cart && @current_cart.products.where(id: @product.id).any? %>
    <div class="rounded-lg p-3 font-semibold text-center text-xl bg-gray-400 hover:bg-gray-500 mr-auto w-full">
      Already in Cart
    </div>
  <% else %>
    <%= link_to "Add to Cart", carts_path(product_id: @product.id), class: "rounded-lg p-3 font-semibold text-center text-xl bg-gray-400 hover:bg-gray-500 mr-auto w-full",
        data: {turbo_method: 'post'} %>
  <% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul class="list-disc ml-6">
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full bg-gray-200", 
                                        {"border-gray-600 focus:outline-blue-600": product.errors[:name].none?, 
                                        "border-red-400 focus:outline-red-600": product.errors[:name].any?}] %>
  </div>

  <div class="my-5">
  <%= form.label :category_id, "Category" %>
  <%= form.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name', product.category_id), { include_blank: true }, 
    class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 bg-gray-200 w-auto", 
            {"border-gray-600 focus:outline-blue-600": product.errors[:category].none?, 
             "border-red-400 focus:outline-red-600": product.errors[:category].any?}] %>
  </div>


  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_textarea :description, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full bg-gray-200", 
                                                  {"border-gray-600 focus:outline-blue-600": product.errors[:description].none?, 
                                                  "border-red-400 focus:outline-red-600": product.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: ["block shadow rounded-md border border-gray-400 
                                                          outline-none px-3 py-2 mt-2 w-auto text-white bg-blue-500"] %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-auto bg-gray-200", 
                                        {"border-gray-600 focus:outline-blue-600": product.errors[:price].none?, 
                                        "border-red-400 focus:outline-red-600": product.errors[:price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: ["rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 
                            text-white inline-block font-medium cursor-pointer"] %>
  </div>
<% end %>

app/views/products/_product.html.erb
<%= link_to product do %> 
  <div id="<%= dom_id product %>" class="w-50 mx-auto mt-5">
    <% if product.images.attached? %>
      <%= image_tag product.images.first, class: "w-50 h-70 object-cover rounded-lg hover:brightness-75 transition-all duration-250" %>
    <% else %>
      <%= image_tag "placeholder.jpg", class: "w-50 h-70 object-cover rounded-lg", alt: "No Image" %> 
      <p class="text-sm text-gray-500 mt-2">Imagem não disponível</p> 
    <% end %>
    <p class="text-lg text-blue-900 font-bold"><%= product.name %></p>
    <p class="text-lg"><%= number_to_currency product.price %></p>
  </div>
<% end %>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<% content_for :title, "The Best Books" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  
  <h1 class="custom-heading">The Best Books</h1>
  

  <%= link_to "Shop by Category", categories_path, class: "ml-10 rounded-lg h-64 w-full border border-gray-700 border-2 bg-gray-200 text-2xl text-blue-800 font-semibold p-2 hover:bg-gray-50" %>

  <div id="products" class="mt-8 min-w-full grid md:grid-cols-4 gap-8">
    <% if @products.any? %>
      <% @products.each do |product| %>
        <div class="shadow p-2"> <%= render product %> </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No products found.</p>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full mb-8">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to Admin", admin_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="max-w-7xl w-full mx-auto px-10 mb-2"> 
    <%= link_to "Products", products_path, class: "text-xl text-blue-800 hover:text-blue-200" %>
    <% if @product.category.present? %>
      <%= link_to "> #{@product.category.name}", @product.category, class: "text-xl text-blue-800 hover:text-blue-200" %>
    <% else %>
      <%= link_to "> Uncategorized", uncategorized_products_path, class: "text-xl text-blue-800 hover:text-blue-200" %>
     <% end %>
    <%= link_to "> #{@product.name}", @product, class: "text-xl text-blue-600" %>
  </div>
  
  <div class="grid md:grid-cols-2">
    <div class="max-w-md w-full mx-auto shadow rounded-lg p-2"> 
      <% if @product.images.any? %>
        <%= image_tag @product.images.first, class: "w-auto h-auto object-cover mx-auto rounded-lg mt-8" %>
        <div class="grid grid-cols-3 gap-4 mt-4"> 
          <% @product.images[1..].each do |image| %>
            <%= image_tag image, class: "w-full h-32 object-cover" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="max-w-xl flex flex-col gap-4 mt-8"> 
      <h1 class="text-4xl font-bold text-indigo-900"> <%= @product.name %> </h1>
      <div class="text-gray-700 mr-20"> 
        <%= @product.description %>
      </div>
      <span class="bg-green-500 p-2 rounded-lg font-semibold text-lg text-green-50 mr-auto"> <%= number_to_currency @product.price %> </span>
      <div class="flex justify-between gap-8">
        <%= link_to "Buy Now", product_buy_now_path(@product), class: "rounded-lg p-3 font-semibold text-center text-xl bg-yellow-400 hover:bg-yellow-500 mr-auto w-full" %>
        <%= render 'add_to_cart', product: @product %>
      </div>
    </div>
  </div>

  <% if current_admin %>
    <div class="w-full flex justify-center items-center mt-16 mb-16 gap-4">
      <%= link_to "Edit this product", edit_product_path(@product), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Back to products", products_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= button_to "Destroy this product", @product, method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  <% end %>
</div>

app/views/products/uncategorized.html.erb
<% content_for :title, "Uncategorized Products" %>

<div class="w-full">
  <h1 class="text-2xl font-bold mb-4">Uncategorized Products</h1>

  <% if @products.any? %>
    <div class="grid md:grid-cols-4 gap-8">
      <% @products.each do |product| %>
        <div class="p-4 rounded-lg shadow hover:shadow-lg">
          <% if product.images.any? %>
            <%= image_tag product.images.first, class: "w-50 h-50 object-cover mx-auto rounded-lg" %>
          <% else %>
            <div class="w-full h-48 flex items-center justify-center bg-gray-100 text-gray-500 rounded-lg">
              No Image Available
            </div>
          <% end %>

          <h2 class="text-lg font-semibold mt-4 text-blue-800">
            <%= link_to product.name, product_path(product) %>
          </h2>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="text-center my-10">No products without a category.</p>
  <% end %>
</div>