config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :admins
  resources :products do
    collection do
      get "uncategorized", to: "products#uncategorized"
    end
    resource :buy_now, only: %i[ show create ], controller: :buy_now do # controller adicionado para que não fique automaticamente no plural
      get "success", on: :collection
    end
  end

  resources :carts, only: %i[ show create destroy ] do
    get "checkout", on: :member, to: "carts#checkout" # member to add the specific id to the url (carts/:id/checkout)
    post "stripe_session", on: :member, to: "carts#stripe_session"
    get "success", on: :member, to: "carts#success"
  end

  resource :admin, only: [ :show ], controller: :admin

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  root "products#index"
end

app/views/layouts/_cart.html.erb
<div class="relative" id="cart">
  <%= image_tag('carrinho.png')%>
  <% if cart && cart.cart_items.any? %>
    <div class="absolute -top-1 -right-3 bg-red-500 px-1.5 text-sm text-white rounded-lg">
      <%= cart.cart_items.count%>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="h-16 w-full fixed top-0 bg-gray-800  z-50">
  <div class="max-w-7xl h-full w-full mx-auto flex items-center justify-between p-8">
    <%= link_to root_path, class: 'flex items-end gap-4' do %>
      <%= image_tag('books.png', class:'w-10 object-cover') %>
      <span class="text-2xl text-gray-100"> The Best Books </span>
    <% end %>

    <%= link_to cart_path(@current_cart.secret_id) do %>
      <%= render "layouts/cart", cart: @current_cart %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ecommerce Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="stripe-pk" content="<%= Rails.application.credentials.dig(:stripe, :pk) %>">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body class="bg-gradient-to-r from-indigo-400 via-purple-300 to-indigo-200">
    <%= render "layouts/navbar" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>